### ISSUE TITLE
Add "checklist" to talk repo issue template 

### ISSUE THREAD

**Issue by iayanpahwa** [ILUGD/volunteers-tasks#11]
[Adopted from Python Pune](https://github.com/pythonpune/meetup-talks/issues/new?assignees=&labels=talk-proposal&template=propose-a-talk.md&title=)

```
 Checklist
Place an '[x]' (no spaces) in all the fields you agree to. You can keep the fields blank on which you don't agree

The talk/workshop speaker agrees to,
- [ ] Share the slides, code snippets and other material used during the talk
- [ ] If the talk is recorded, you grant the permission to release the video on ILUGD's YouTube channel(LINK) under [CC-BY-4.0 license](https://creativecommons.org/licenses/by/4.0/)
- [ ] Not do any hiring pitches during the talk and follow the Code of Conduct(LINK TO COC)
```

**Comment by nk521** [comment]
Assign this to @thesage21

CC @xeon-zolt @iayanpahwa

**Comment by theSage21** [comment]
Got it
